version: '3'

services:
  databases:
    image: mysql
    ports:
    - "33061:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=sai
