version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
       - BUILD_DATE=$BUILD_DATE
       - GIT_HASH=$GIT_HASH 
    ports:
      - 8080:8080
    command: npm run dev
