# The line below states we will base our new image on the Latest Official Ubuntu 
FROM node:latest
 
#
# Identify the maintainer of an image
MAINTAINER My Name "venkatasaisoft@gmail.com"
 
#
# Install NGINX to test.
RUN apt-get update -y
RUN npm install -g @vue/cli-service
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN pip3 install awscli
